suppress-self-cert-warning: true
database:
  use: mysql
  mysql:
    url: db:3306
    username: empire
    password: simplego422
    database_name: empire
  sqlite:
    location: empire/server/data/empire.db
  defaults:
    # staging key will first look at OS environment variables, then here.
    # If empty, will be prompted (like Empire <3.7).
    staging-key: RANDOM
    username: empire
    password: simplego422
    obfuscation:
      - language: powershell
        enabled: false
        command: "Token\\All\\1"
        module: "invoke-obfuscation"
        preobfuscatable: true
      - language: csharp
        enabled: false
        command: ""
        module: "confuser"
        preobfuscatable: false
    keyword_obfuscation:
      - Invoke-Empire
      - Invoke-Mimikatz
    # an IP white list to ONLY accept clients from
    #   format is "192.168.1.1,192.168.1.10-192.168.1.100,10.0.0.0/8"
    ip-whitelist: ""
    # an IP black list to reject accept clients from
    #   format is "192.168.1.1,192.168.1.10-192.168.1.100,10.0.0.0/8"
    ip-blacklist: ""
starkiller:
  repo: https://github.com/BC-SECURITY/Starkiller.git
  # Can be a branch, tag, or commit hash
  ref: v2.5.3
  # for private-main, instead of updating the submodule, just work out of a local copy.
  # So devs can work off the latest changes and not worry about accidentally updating the submodule
  # for the downstream main branches.
  use_temp_dir: false
  auto_update: true
plugins:
  # Auto-load plugin with defined settings
  csharpserver:
    status: start
directories:
  downloads: empire/server/downloads/
  module_source: empire/server/data/module_source/
  obfuscated_module_source: empire/server/data/obfuscated_module_source/
logging:
  level: INFO
  directory: empire/server/downloads/logs/
  simple_console: true
debug:
  last_task:
    enabled: false
    file: empire/server/data/last_task.txt
