version: '3.4'

services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/ttyUSB0:/dev/ttyUSB69
    volumes:
      - octoprint:/octoprint
    networks:
      - secureprinting

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - secureprinting
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
        uid: '0'
        gid: '0'
        mode: 440
    secrets:
      - source: ssl_password
        target: /etc/ssl_password.txt
        uid: '0'
        gid: '0'
        mode: 440
      - source: ssl_cert
        target: /etc/nginx/conf.d/cert.pem
        uid: '0'
        gid: '0'
        mode: 440
      - source: ssl_key
        target: /etc/nginx/conf.d/key.pem
        uid: '0'
        gid: '0'
        mode: 440
    networks:
      - https

  secureprinting:
    image: secureprinting
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    restart: unless-stopped
    volumes:
      - configs:/app/data:rw
      - uploads:/app/uploads:rw
    environment:
      - OCTOPRINT_URL=http://octoprint:80
      - OCTOPRINT_APIKEY=${OCTOPRINT_APIKEY}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost}
    networks:
      - secureprinting
      - https
    logging:
      driver: syslog
      options:
        syslog-address: "${SYSLOG_ADDRESS}"

configs:
  nginx_conf:
    file: ./nginx/default.conf

secrets:
  ssl_password:
    file: ./nginx/ssl_password.txt
  ssl_cert:
    file: ./nginx/cert.pem
  ssl_key:
    file: ./nginx/cert.key

volumes:
  octoprint: {}
  configs: {}
  uploads: {}

networks:
  secureprinting:
    internal: true
  https:
    internal: true
